### PR TITLE
added --counter-token option

### PR DESCRIPTION
**Pull request by hellmanj**

### CODE REVIEW

**Comment by dpsfrishberg** [comment]
Nice work!

**Comment by kahunacohen** [comment]
:+1:  cool!

**Comment by kahunacohen** [comment]
Are you going to merge and push to pypi or do you want me to?

**Comment by hellmanj** [comment]
Sorry, I responded to this yesterday but never hit the green button.  It looks like you did the release already which is great.  I don't think I'm an owner in PyPI on this one anyway.  If you add me, maybe I can get travis going on this too.

**Comment by kahunacohen** [comment]
Yeah I did the release last night. Remind me tomorrow and I'll add you.

**Pull request merged**
